### ISSUE TITLE
Using Transform2DEffect with BackdropBrush

### ISSUE THREAD

**Issue by nesherhh** [Microsoft/WindowsCompositionSamples#294]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[x] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior

System.ArgumentException
  HResult=0x80070057
  Message=Falscher Parameter.

Invalid argument to parameter value. Backdrop brushes cannot be transformed.
  Source=Windows
  StackTrace:
   at Windows.UI.Composition.CompositionEffectBrush.SetSourceParameter(String name, CompositionBrush source)
   at OffsetEffectTest.OffsetBrush.OnConnected() in C:\temp\OffsetEffectTest\OffsetEffectTest\OffsetBrush.cs:line 37

## Expected Behavior

I'm trying to make a brush that takes a BackdropBrush, makes offset in X coordinate and combines the result with the original BackdropBrush. So it like same image doubled and shifted on X.
But I get the Exception that Transform2DEffect (win2d) can't be used with BackdropBrush. How do I make transformation to the BackdropBrush?

##  Your Environment

* SDK #:  17134
* Operating System build # :  17134.112
* Visual Studio Version # : 15.7.4

**Comment by krenner** [comment]
@nesherhh Sorry I didn't answer this sooner.  We have a very specific solution we use for optimizing BackdropBrush and could not guarantee good results with transforms so we unfortunately prevent that case.  Do you have a sketch or comp of what you want these effects to look like?  There could be another option using something like blend modes and opacity if you don’t require effects drawn on contents underneath a visual.

**Comment by krenner** [comment]
Closing due to inactivity, please re-open if needed.
